# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "articles", :force => true do |t|
    t.column "page_id",              :integer
    t.column "article_title",        :string
    t.column "article_author",       :string
    t.column "article_public_text",  :text
    t.column "article_private_text", :text
    t.column "article_weight",       :integer
    t.column "created_on",           :datetime
    t.column "updated_on",           :datetime
  end

  create_table "pages", :force => true do |t|
    t.column "site_id",     :integer
    t.column "page_title",  :string
    t.column "page_author", :string
    t.column "page_about",  :string
    t.column "page_weight", :integer
    t.column "created_on",  :datetime
    t.column "updated_on",  :datetime
  end

  create_table "schema_migrations", :id => false, :force => true do |t|
    t.column "version", :string, :default => "", :null => false
  end

  add_index "schema_migrations", ["version"], :name => "unique_schema_migrations", :unique => true

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "sites", :force => true do |t|
    t.column "contact",    :string
    t.column "sitename",   :string
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "created_at",    :datetime
  end

  add_index "taggings", ["tag_id"], :name => "index_taggings_on_tag_id"
  add_index "taggings", ["taggable_id", "taggable_type"], :name => "index_taggings_on_taggable_id_and_taggable_type"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
